version: "3"

services:
  subspace-metadata:
    build:
      dockerfile: Dockerfile
      context: ./subspace-metadata/
    restart: unless-stopped
    read_only: true
    environment:
      SUBSCAN_API_KEY: ${SUBSCAN_API_KEY}
    ports:
      - 127.0.0.1:8080:8080
    expose:
      - 8080

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend/
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /var/cache/nginx:uid=101,gid=101
      - /var/run:uid=101,gid=101
      - /app/tmp:uid=101,gid=101
    environment:
      SUBSTRATE_TELEMETRY_URL: wss://telemetry.subspace.network/feed
      SUBSPACE_API_URL: https://telemetry.subspace.network/api
      DISABLE_NODE_LIST: 0
    ports:
      - 127.0.0.1:3000:8000
    expose:
      - 3000

  shard0: &shard
    build:
      dockerfile: Dockerfile
      context: ./backend/
    restart: unless-stopped
    read_only: true
    command: [
      'telemetry_shard',
      '--listen', '0.0.0.0:80',
      '--core', 'http://core:8000/shard_submit'
    ]
    ports:
      - 127.0.0.1:8001:80
    expose:
      - 8001

  shard1:
    <<: *shard
    ports:
      - 127.0.0.1:8002:80
    expose:
      - 8002

  core:
    build:
      dockerfile: Dockerfile
      context: ./backend/
    restart: unless-stopped
    read_only: true
    command: [
      'telemetry_core',
      '--listen', '0.0.0.0:8000',
      '--max-third-party-nodes', '100000',
      '--update-every', '1',
    ]
    ports:
      - 127.0.0.1:8000:8000
    expose:
      - 8000
